### ISSUE TITLE
Test dependency on List::Lazy, which requires perl 5.22

### ISSUE THREAD

**Issue by Grinnz** [yanick/Dist-Zilla-Plugin-SchwartzRatio#4]
This currently makes the dist's minimum version 5.22.

**Comment by yanick** [comment]
Yup, that's know, and not seen as a problem. I reckon that a dzil plugin is used by authors, and if anybody should keep abreast of perl versions, it should be cpan authors.

Plus, it's a module that is more gravy on the side than core dzil functionality, so if somebody doesn't want to go 5.22+, well, they can just not use the module. No biggie.

**Comment by Grinnz** [comment]
I only bring it up because the last release of this module had a change to drop the minimum version down to 5.14, but this prevents that.
